[env]
TERM = "alacritty"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations_theme_variant = "Dark"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"

[general]

import= [
    "~/.config/alacritty/themes/challenger_deep.toml"
]
