vim.opt.nu = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.autoindent = true
vim.opt.wrap = true
vim.opt.linebreak = true
vim.opt.undofile = true
vim.opt.incsearch = true
vim.opt.relativenumber=true
--vim.opt.nocompatible = true
--vim.opt.cc=80
vim.opt.syntax=ON
vim.opt.clipboard=unnamedplus
